import type { Category, HousePlan } from "@/types"

export const mockCategories: Category[] = [
  { id: "1", name: "Modern", name_th: "โมเดิร์น", slug: "modern", plan_count: 24 },
  { id: "2", name: "Tropical", name_th: "ทรอปิคอล", slug: "tropical", plan_count: 18 },
  { id: "3", name: "Contemporary", name_th: "คอนเทมโพรารี", slug: "contemporary", plan_count: 15 },
  { id: "4", name: "Traditional Thai", name_th: "ไทยประยุกต์", slug: "thai", plan_count: 12 },
  { id: "5", name: "Loft", name_th: "ลอฟต์", slug: "loft", plan_count: 9 },
  { id: "6", name: "Minimalist", name_th: "มินิมอล", slug: "minimalist", plan_count: 21 },
]

export const mockPlans: HousePlan[] = [
  {
    id: "1",
    title: "บ้านโมเดิร์น M-101",
    slug: "modern-m101",
    description: "แบบบ้านโมเดิร์นสไตล์มินิมอล เส้นสายเรียบง่าย ตอบโจทย์ชีวิตคนยุคใหม่ ระเบียงกว้าง วัสดุคุณภาพสูง",
    floors: 2,
    bedrooms: 3,
    bathrooms: 3,
    kitchens: 1,
    living_rooms: 1,
    garages: 1,
    total_area_sqm: 185,
    is_featured: true,
    is_available: true,
    view_count: 342,
    created_at: "2024-01-15",
    category: { id: "1", name: "Modern", name_th: "โมเดิร์น", slug: "modern" },
  },
  {
    id: "2",
    title: "บ้านทรอปิคอล T-203",
    slug: "tropical-t203",
    description: "บ้านสไตล์ทรอปิคอล เปิดโล่ง รับลม เน้นพื้นที่สีเขียวรอบบ้าน เหมาะกับอากาศเมืองไทย",
    floors: 1,
    bedrooms: 3,
    bathrooms: 2,
    kitchens: 1,
    living_rooms: 2,
    garages: 1,
    total_area_sqm: 145,
    is_featured: true,
    is_available: true,
    view_count: 287,
    created_at: "2024-01-20",
    category: { id: "2", name: "Tropical", name_th: "ทรอปิคอล", slug: "tropical" },
  },
  {
    id: "3",
    title: "บ้านคอนเทมโพรารี C-305",
    slug: "contemporary-c305",
    description: "ดีไซน์ร่วมสมัย มิกซ์วัสดุหลากหลาย ทั้งไม้ กระจก คอนกรีต บรรยากาศ Resort Style",
    floors: 3,
    bedrooms: 4,
    bathrooms: 4,
    kitchens: 1,
    living_rooms: 2,
    garages: 2,
    total_area_sqm: 280,
    is_featured: true,
    is_available: true,
    view_count: 198,
    created_at: "2024-02-01",
    category: { id: "3", name: "Contemporary", name_th: "คอนเทมโพรารี", slug: "contemporary" },
  },
  {
    id: "4",
    title: "บ้านมินิมอล MN-102",
    slug: "minimalist-mn102",
    description: "เรียบง่ายแต่สวยงาม ใช้วัสดุคุณภาพสูง เน้นพื้นที่ใช้สอยสูงสุด ไม่มีของฟุ่มเฟือย",
    floors: 1,
    bedrooms: 2,
    bathrooms: 2,
    kitchens: 1,
    living_rooms: 1,
    garages: 0,
    total_area_sqm: 120,
    is_featured: false,
    is_available: true,
    view_count: 156,
    created_at: "2024-02-10",
    category: { id: "6", name: "Minimalist", name_th: "มินิมอล", slug: "minimalist" },
  },
  {
    id: "5",
    title: "บ้านไทยประยุกต์ TH-401",
    slug: "thai-th401",
    description: "ผสมผสานความงามสถาปัตยกรรมไทย กับฟังก์ชันการใช้งานสมัยใหม่ หลังคาจั่ว ระเบียงไทย",
    floors: 2,
    bedrooms: 4,
    bathrooms: 3,
    kitchens: 1,
    living_rooms: 2,
    garages: 2,
    total_area_sqm: 240,
    is_featured: false,
    is_available: true,
    view_count: 203,
    created_at: "2024-02-15",
    category: { id: "4", name: "Traditional Thai", name_th: "ไทยประยุกต์", slug: "thai" },
  },
  {
    id: "6",
    title: "บ้านลอฟต์ L-501",
    slug: "loft-l501",
    description: "สไตล์อินดัสเทรียล เพดานสูง โครงสร้างโชว์ วัสดุดิบ เหล็ก ปูน ไม้ ดูมีชีวิตชีวา",
    floors: 2,
    bedrooms: 3,
    bathrooms: 3,
    kitchens: 1,
    living_rooms: 1,
    garages: 1,
    total_area_sqm: 210,
    is_featured: true,
    is_available: true,
    view_count: 267,
    created_at: "2024-02-20",
    category: { id: "5", name: "Loft", name_th: "ลอฟต์", slug: "loft" },
  },
]

export const USE_MOCK_DATA =
  !process.env.NEXT_PUBLIC_SUPABASE_URL ||
  process.env.NEXT_PUBLIC_SUPABASE_URL === "https://your-project.supabase.co"
